# Generated by Django 4.0.3 on 2022-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COOPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('entity_name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('advertisement', models.ImageField(blank=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='IntershipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('entity_name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('advertisement', models.ImageField(blank=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='MinorsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_in', models.CharField(choices=[('Artifical Intelligence (AI)', 'Artifical Intelligence (AI)'), ('Cyber Security (FC)', 'Cyber Security (FC)')], max_length=50)),
                ('plan', models.ImageField(blank=True, upload_to=None)),
            ],
        ),
    ]
