# Generated by Django 4.0.3 on 2022-05-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SE_Program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intershipinfo',
            options={'verbose_name': 'Intership Information'},
        ),
    ]
