# Generated by Django 4.0.3 on 2022-05-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SE_Program', '0002_alter_intershipinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coopinfo',
            options={'verbose_name': 'COOP Information'},
        ),
        migrations.AlterModelOptions(
            name='minorsinfo',
            options={'verbose_name': 'Minors Information'},
        ),
    ]
