# Generated by Django 4.0.4 on 2022-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Snapchat', 'Snapchat'), ('Twitter', 'Twitter')], max_length=255)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'ordering': ['platform_name'],
            },
        ),
    ]
